#! /nix/store/nshgh2svh4a5z1vqfvbqq2dnvgfq59ka-bash-4.3-p33/bin/bash -e
export PATH=/nix/store/a5fvpqib15lhhjr1pfzm6arvf04idi5c-faust-8-1-2015/bin:/nix/store/2sal301ijn8dgl3virqfxwh5x5m87mj0-xdg-utils-1.1.0-rc3p7/bin${PATH:+:}$PATH
exec /nix/store/9v7v22y8jr5ypn32ysnhlaznr63dif60-faust2firefox-8-1-2015/bin/.faust2firefox-wrapped "${extraFlagsArray[@]}" "$@"
