#! /nix/store/disi5277lygfj6m7m3ajwvvp9mqdp4la-bash-4.3-p42/bin/bash -e
export PATH=/nix/store/c035ds7v0n9kc7plqf24vphy8dgf2a0i-faust-8-1-2015/bin:/nix/store/lakrzxg73ydwcr07y2rn4f5lgw7gyl4z-xdg-utils-1.1.0-rc3p46/bin${PATH:+:}$PATH
exec -a "$0" /nix/store/qkzrjp22ja7wnzv3y8p1pwsh6xfgfaba-faust2firefox-8-1-2015/bin/.faust2firefox-wrapped "${extraFlagsArray[@]}" "$@"
