#!/usr/bin/env bash
# a NixOS friendly prompt

#////////////////////////////////////////////////////////
# startup script for the Karplus-Strong synth plus pitchtracker
#////////////////////////////////////////////////////////

current_synth=Karplus-StrongSinger
source synthWrapper
