#!/usr/bin/env bash
# a NixOS friendly prompt


#////////////////////////////////////////////////////////
# startup script for the classic vocoder plus FX plus pitchtracker
#////////////////////////////////////////////////////////


./stringSinger &
synth_pid=$!
sleep 5 &&
jack_connect system:capture_1 stringSinger:in_0 &&

# If this script is killed, kill everything.
trap "kill -- -$$" EXIT

pd -nodac -nomidi -nogui ~/faust/VoiceOfFaust/PureData/OscSendVoc.pd &

wait $synth_pid
kill -- -$$
