#!/usr/bin/env bash
# a NixOS friendly prompt

#////////////////////////////////////////////////////////
# startup script for the KarplusStrong synth plus pitchtracker
#////////////////////////////////////////////////////////

current_synth=KarplusStrongSinger
source synthWrapper
